// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PVaultServiceClient is the client API for PVaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PVaultServiceClient interface {
	// Vault Management
	CreateVault(ctx context.Context, in *CreateVaultRequest, opts ...grpc.CallOption) (*CreateVaultResponse, error)
	// Membership Management
	CreateMembership(ctx context.Context, in *CreateMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	ListAuthorizedVaults(ctx context.Context, in *ListVaultsRequest, opts ...grpc.CallOption) (*ListVaultsResponse, error)
	// Secret Management
	ProtectSecret(ctx context.Context, in *ProtectSecretRequest, opts ...grpc.CallOption) (*SecretResponse, error)
	UncoverSecret(ctx context.Context, in *UncoverSecretRequest, opts ...grpc.CallOption) (*UncoverSecretResponse, error)
	UpdateSecretCapabilities(ctx context.Context, in *UpdateSecretCapabilitiesRequest, opts ...grpc.CallOption) (*SecretResponse, error)
	// Audit Logging
	RecordAuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error)
	GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
}

type pVaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPVaultServiceClient(cc grpc.ClientConnInterface) PVaultServiceClient {
	return &pVaultServiceClient{cc}
}

func (c *pVaultServiceClient) CreateVault(ctx context.Context, in *CreateVaultRequest, opts ...grpc.CallOption) (*CreateVaultResponse, error) {
	out := new(CreateVaultResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/CreateVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) CreateMembership(ctx context.Context, in *CreateMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/CreateMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) ListAuthorizedVaults(ctx context.Context, in *ListVaultsRequest, opts ...grpc.CallOption) (*ListVaultsResponse, error) {
	out := new(ListVaultsResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/ListAuthorizedVaults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) ProtectSecret(ctx context.Context, in *ProtectSecretRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/ProtectSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) UncoverSecret(ctx context.Context, in *UncoverSecretRequest, opts ...grpc.CallOption) (*UncoverSecretResponse, error) {
	out := new(UncoverSecretResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/UncoverSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) UpdateSecretCapabilities(ctx context.Context, in *UpdateSecretCapabilitiesRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/UpdateSecretCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) RecordAuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error) {
	out := new(AuditLogResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/RecordAuditLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pVaultServiceClient) GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, "/pvault.v1.PVaultService/GetAuditLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PVaultServiceServer is the server API for PVaultService service.
// All implementations must embed UnimplementedPVaultServiceServer
// for forward compatibility
type PVaultServiceServer interface {
	// Vault Management
	CreateVault(context.Context, *CreateVaultRequest) (*CreateVaultResponse, error)
	// Membership Management
	CreateMembership(context.Context, *CreateMembershipRequest) (*MembershipResponse, error)
	ListAuthorizedVaults(context.Context, *ListVaultsRequest) (*ListVaultsResponse, error)
	// Secret Management
	ProtectSecret(context.Context, *ProtectSecretRequest) (*SecretResponse, error)
	UncoverSecret(context.Context, *UncoverSecretRequest) (*UncoverSecretResponse, error)
	UpdateSecretCapabilities(context.Context, *UpdateSecretCapabilitiesRequest) (*SecretResponse, error)
	// Audit Logging
	RecordAuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error)
	GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error)
	mustEmbedUnimplementedPVaultServiceServer()
}

// UnimplementedPVaultServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPVaultServiceServer struct {
}

func (UnimplementedPVaultServiceServer) CreateVault(context.Context, *CreateVaultRequest) (*CreateVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVault not implemented")
}
func (UnimplementedPVaultServiceServer) CreateMembership(context.Context, *CreateMembershipRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembership not implemented")
}
func (UnimplementedPVaultServiceServer) ListAuthorizedVaults(context.Context, *ListVaultsRequest) (*ListVaultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthorizedVaults not implemented")
}
func (UnimplementedPVaultServiceServer) ProtectSecret(context.Context, *ProtectSecretRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProtectSecret not implemented")
}
func (UnimplementedPVaultServiceServer) UncoverSecret(context.Context, *UncoverSecretRequest) (*UncoverSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UncoverSecret not implemented")
}
func (UnimplementedPVaultServiceServer) UpdateSecretCapabilities(context.Context, *UpdateSecretCapabilitiesRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecretCapabilities not implemented")
}
func (UnimplementedPVaultServiceServer) RecordAuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordAuditLog not implemented")
}
func (UnimplementedPVaultServiceServer) GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedPVaultServiceServer) mustEmbedUnimplementedPVaultServiceServer() {}

// UnsafePVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PVaultServiceServer will
// result in compilation errors.
type UnsafePVaultServiceServer interface {
	mustEmbedUnimplementedPVaultServiceServer()
}

func RegisterPVaultServiceServer(s grpc.ServiceRegistrar, srv PVaultServiceServer) {
	s.RegisterService(&PVaultService_ServiceDesc, srv)
}

func _PVaultService_CreateVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).CreateVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/CreateVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).CreateVault(ctx, req.(*CreateVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_CreateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).CreateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/CreateMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).CreateMembership(ctx, req.(*CreateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_ListAuthorizedVaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVaultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).ListAuthorizedVaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/ListAuthorizedVaults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).ListAuthorizedVaults(ctx, req.(*ListVaultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_ProtectSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).ProtectSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/ProtectSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).ProtectSecret(ctx, req.(*ProtectSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_UncoverSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncoverSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).UncoverSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/UncoverSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).UncoverSecret(ctx, req.(*UncoverSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_UpdateSecretCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).UpdateSecretCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/UpdateSecretCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).UpdateSecretCapabilities(ctx, req.(*UpdateSecretCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_RecordAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).RecordAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/RecordAuditLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).RecordAuditLog(ctx, req.(*AuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PVaultService_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVaultServiceServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pvault.v1.PVaultService/GetAuditLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVaultServiceServer).GetAuditLogs(ctx, req.(*GetAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PVaultService_ServiceDesc is the grpc.ServiceDesc for PVaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PVaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pvault.v1.PVaultService",
	HandlerType: (*PVaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVault",
			Handler:    _PVaultService_CreateVault_Handler,
		},
		{
			MethodName: "CreateMembership",
			Handler:    _PVaultService_CreateMembership_Handler,
		},
		{
			MethodName: "ListAuthorizedVaults",
			Handler:    _PVaultService_ListAuthorizedVaults_Handler,
		},
		{
			MethodName: "ProtectSecret",
			Handler:    _PVaultService_ProtectSecret_Handler,
		},
		{
			MethodName: "UncoverSecret",
			Handler:    _PVaultService_UncoverSecret_Handler,
		},
		{
			MethodName: "UpdateSecretCapabilities",
			Handler:    _PVaultService_UpdateSecretCapabilities_Handler,
		},
		{
			MethodName: "RecordAuditLog",
			Handler:    _PVaultService_RecordAuditLog_Handler,
		},
		{
			MethodName: "GetAuditLogs",
			Handler:    _PVaultService_GetAuditLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/pvault.proto",
}
